version: "2"

run:
  timeout: 10m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
  settings:
    staticcheck:
      checks:
        - "all"
  exclusions:
    paths:
      - vendor
    generated: strict

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/faroshq/faros-kedge
