run:
  timeout: 10m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/faroshq/faros-kedge

issues:
  exclude-dirs:
    - vendor
  exclude-generated: strict
