hub:
  hubExternalURL: "https://hub.faros.sh"
  devMode: false
  embeddedGraphQL: true

  # Authentication - choose one:
  # 
  staticAuthTokens:
    - "f782d49d86e73e5b9"  # Simple option
  # OR use OIDC (see Security docs)

  tls:
    selfSigned:
      enabled: false
    certManager:
      enabled: true
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
        - "hub.faros.sh"

ingress:
  enabled: true
  className: "cloudflare-tunnel"
  annotations:
    cloudflare-tunnel-ingress-controller.strrl.dev/proxy-ssl-verify: "off"
    cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: "https"
  hosts:
    - host: hub.faros.sh
      paths:
        - path: /
          pathType: ImplementationSpecific