//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironment) DeepCopyInto(out *DevEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironment.
func (in *DevEnvironment) DeepCopy() *DevEnvironment {
	if in == nil {
		return nil
	}
	out := new(DevEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironmentList) DeepCopyInto(out *DevEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironmentList.
func (in *DevEnvironmentList) DeepCopy() *DevEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(DevEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironmentRuntime) DeepCopyInto(out *DevEnvironmentRuntime) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironmentRuntime.
func (in *DevEnvironmentRuntime) DeepCopy() *DevEnvironmentRuntime {
	if in == nil {
		return nil
	}
	out := new(DevEnvironmentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironmentSpec) DeepCopyInto(out *DevEnvironmentSpec) {
	*out = *in
	out.Runtime = in.Runtime
	out.Sync = in.Sync
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironmentSpec.
func (in *DevEnvironmentSpec) DeepCopy() *DevEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(DevEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironmentStatus) DeepCopyInto(out *DevEnvironmentStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironmentStatus.
func (in *DevEnvironmentStatus) DeepCopy() *DevEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(DevEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevEnvironmentSync) DeepCopyInto(out *DevEnvironmentSync) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevEnvironmentSync.
func (in *DevEnvironmentSync) DeepCopy() *DevEnvironmentSync {
	if in == nil {
		return nil
	}
	out := new(DevEnvironmentSync)
	in.DeepCopyInto(out)
	return out
}
