{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kro-mc.serviceAccountName" . }}
  labels:
    {{- include "kro-mc.labels" . | nindent 4 }}
{{- end }}
