apiVersion: v2
name: kedge-hub
description: Kedge Hub - multi-tenant edge control plane (kcp + kedge-hub)
type: application
version: v0.0.5
appVersion: "v0.0.5"
home: https://github.com/faroshq/kedge
sources:
  - https://github.com/faroshq/kedge
maintainers:
  - name: Faros Authors
dependencies:
  - name: kubernetes-graphql-gateway
    version: "0.0.1"
    repository: "oci://ghcr.io/faroshq/charts"
    condition: kubernetes-graphql-gateway.enabled
