//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntry) DeepCopyInto(out *CatalogEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntry.
func (in *CatalogEntry) DeepCopy() *CatalogEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryList) DeepCopyInto(out *CatalogEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryList.
func (in *CatalogEntryList) DeepCopy() *CatalogEntryList {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntrySpec) DeepCopyInto(out *CatalogEntrySpec) {
	*out = *in
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProviderUI)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(ProviderBackend)
		**out = **in
	}
	if in.VirtualWorkspace != nil {
		in, out := &in.VirtualWorkspace, &out.VirtualWorkspace
		*out = new(ProviderVirtualWorkspace)
		**out = **in
	}
	if in.APIExport != nil {
		in, out := &in.APIExport, &out.APIExport
		*out = new(ProviderAPIExport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntrySpec.
func (in *CatalogEntrySpec) DeepCopy() *CatalogEntrySpec {
	if in == nil {
		return nil
	}
	out := new(CatalogEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryStatus) DeepCopyInto(out *CatalogEntryStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ProviderEndpoints)
		**out = **in
	}
	if in.KubeconfigSecret != nil {
		in, out := &in.KubeconfigSecret, &out.KubeconfigSecret
		*out = new(KubeconfigSecretRef)
		**out = **in
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryStatus.
func (in *CatalogEntryStatus) DeepCopy() *CatalogEntryStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSecretRef) DeepCopyInto(out *KubeconfigSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSecretRef.
func (in *KubeconfigSecretRef) DeepCopy() *KubeconfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAPIExport) DeepCopyInto(out *ProviderAPIExport) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]ProviderAPIResourceSchema, len(*in))
		copy(*out, *in)
	}
	if in.PermissionClaims != nil {
		in, out := &in.PermissionClaims, &out.PermissionClaims
		*out = make([]ProviderPermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAPIExport.
func (in *ProviderAPIExport) DeepCopy() *ProviderAPIExport {
	if in == nil {
		return nil
	}
	out := new(ProviderAPIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAPIResourceSchema) DeepCopyInto(out *ProviderAPIResourceSchema) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAPIResourceSchema.
func (in *ProviderAPIResourceSchema) DeepCopy() *ProviderAPIResourceSchema {
	if in == nil {
		return nil
	}
	out := new(ProviderAPIResourceSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderBackend) DeepCopyInto(out *ProviderBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderBackend.
func (in *ProviderBackend) DeepCopy() *ProviderBackend {
	if in == nil {
		return nil
	}
	out := new(ProviderBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderEndpoints) DeepCopyInto(out *ProviderEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderEndpoints.
func (in *ProviderEndpoints) DeepCopy() *ProviderEndpoints {
	if in == nil {
		return nil
	}
	out := new(ProviderEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderNavChild) DeepCopyInto(out *ProviderNavChild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderNavChild.
func (in *ProviderNavChild) DeepCopy() *ProviderNavChild {
	if in == nil {
		return nil
	}
	out := new(ProviderNavChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPermissionClaim) DeepCopyInto(out *ProviderPermissionClaim) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPermissionClaim.
func (in *ProviderPermissionClaim) DeepCopy() *ProviderPermissionClaim {
	if in == nil {
		return nil
	}
	out := new(ProviderPermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderUI) DeepCopyInto(out *ProviderUI) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ProviderNavChild, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderUI.
func (in *ProviderUI) DeepCopy() *ProviderUI {
	if in == nil {
		return nil
	}
	out := new(ProviderUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVirtualWorkspace) DeepCopyInto(out *ProviderVirtualWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVirtualWorkspace.
func (in *ProviderVirtualWorkspace) DeepCopy() *ProviderVirtualWorkspace {
	if in == nil {
		return nil
	}
	out := new(ProviderVirtualWorkspace)
	in.DeepCopyInto(out)
	return out
}
