apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: providers.kedge.faros.sh
spec:
  resources:
  - group: providers.kedge.faros.sh
    name: catalogentries
    schema: v260524-1238369.catalogentries.providers.kedge.faros.sh
    storage:
      crd: {}
status: {}
