apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: tenancy.kedge.faros.sh
spec:
  resources:
  - group: tenancy.kedge.faros.sh
    name: memberships
    schema: v260531-014829c.memberships.tenancy.kedge.faros.sh
    storage:
      crd: {}
  - group: tenancy.kedge.faros.sh
    name: organizations
    schema: v260531-fb75204.organizations.tenancy.kedge.faros.sh
    storage:
      crd: {}
  - group: tenancy.kedge.faros.sh
    name: usermembershipindices
    schema: v260601-922907a.usermembershipindices.tenancy.kedge.faros.sh
    storage:
      crd: {}
  - group: tenancy.kedge.faros.sh
    name: users
    schema: v260531-0ae765d.users.tenancy.kedge.faros.sh
    storage:
      crd: {}
status: {}
