apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: mcp.kedge.faros.sh
spec:
  resources:
  - group: mcp.kedge.faros.sh
    name: kubernetesmcps
    schema: v260312-35cac3a.kubernetesmcps.mcp.kedge.faros.sh
    storage:
      crd: {}
status: {}
