apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: mcp.kedge.faros.sh
spec:
  resources:
  - group: mcp.kedge.faros.sh
    name: kubernetes
    schema: v260313-6cb746e.kubernetes.mcp.kedge.faros.sh
    storage:
      crd: {}
status: {}
