apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: edges.kedge.faros.sh
spec:
  resources:
  - group: edges.kedge.faros.sh
    name: kubernetesclusters
    schema: v260715-d4e8aa2.kubernetesclusters.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: linuxservers
    schema: v260715-d4e8aa2.linuxservers.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: placements
    schema: v260716-d4e8aa2.placements.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: services
    schema: v260718-d25eaf2.services.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: workloads
    schema: v260716-d4e8aa2.workloads.edges.kedge.faros.sh
    storage:
      crd: {}
status: {}
