apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: edges.kedge.faros.sh
spec:
  resources:
  - group: edges.kedge.faros.sh
    name: kubernetesclusters
    schema: v260715-d4e8aa2.kubernetesclusters.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: linuxservers
    schema: v260715-d4e8aa2.linuxservers.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: placements
    schema: v260718-e83a64f.placements.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: services
    schema: v260719-be6103f.services.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: edges.kedge.faros.sh
    name: workloads
    schema: v260718-e83a64f.workloads.edges.kedge.faros.sh
    storage:
      crd: {}
status: {}
