apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: agents.kedge.faros.sh
spec:
  resources:
  - group: agents.kedge.faros.sh
    name: agents
    schema: v260714-8e565fc.agents.agents.kedge.faros.sh
    storage:
      crd: {}
  - group: agents.kedge.faros.sh
    name: connections
    schema: v260714-56b44bb.connections.agents.kedge.faros.sh
    storage:
      crd: {}
  - group: agents.kedge.faros.sh
    name: runs
    schema: v260714-9965166.runs.agents.kedge.faros.sh
    storage:
      crd: {}
  - group: agents.kedge.faros.sh
    name: schedules
    schema: v260714-9965166.schedules.agents.kedge.faros.sh
    storage:
      crd: {}
  - group: agents.kedge.faros.sh
    name: toolsets
    schema: v260714-8e565fc.toolsets.agents.kedge.faros.sh
    storage:
      crd: {}
  - group: agents.kedge.faros.sh
    name: triggers
    schema: v260714-d427180.triggers.agents.kedge.faros.sh
    storage:
      crd: {}
status: {}
