#!/usr/bin/env bash
# Creates an edge resource (idempotent) and writes .env.edge.<type> so that
# `make dev-run-edge TYPE=<type>` can pick it up. Per-type files mean a
# kubernetes edge and a server edge can coexist without overwriting each other.
#
# Edges are the standalone `edges` provider now: two kinds under one group
# edges.kedge.faros.sh — KubernetesCluster (type=kubernetes) and LinuxServer
# (type=server) — instead of the old single Edge with spec.type. The workspace
# must have the edges provider ENABLED (APIBinding to edges.providers.kedge.faros.sh)
# for these kinds to exist.
#
# Usage:
#   hack/scripts/dev-edge-setup.sh <edge-name> <type> [labels]
#
#   type: "kubernetes" (k8s cluster agent) or "server" (bare-metal SSH host)
#
# Requires:
#   - kubectl configured to reach the hub (run `make dev-login` first)

set -euo pipefail

EDGE_NAME="${1:?Usage: $0 <edge-name> <type> [labels]}"
EDGE_TYPE="${2:-kubernetes}"
LABELS="${3:-env=dev,provider=local}"

BINDIR="${BINDIR:-bin}"

if [[ "${EDGE_TYPE}" != "kubernetes" && "${EDGE_TYPE}" != "server" ]]; then
  echo "ERROR: type must be 'kubernetes' or 'server', got: ${EDGE_TYPE}" >&2
  exit 1
fi

# Map the type to its kind + resource in group edges.kedge.faros.sh.
if [[ "${EDGE_TYPE}" == "server" ]]; then
  EDGE_KIND="LinuxServer"
  EDGE_RESOURCE="linuxservers"
else
  EDGE_KIND="KubernetesCluster"
  EDGE_RESOURCE="kubernetesclusters"
fi

# Build a metadata.labels block from the comma-separated key=value LABELS.
LABELS_YAML=""
if [[ -n "${LABELS}" ]]; then
  LABELS_YAML=$'\n  labels:'
  IFS=',' read -ra _pairs <<< "${LABELS}"
  for _p in "${_pairs[@]}"; do
    _k="${_p%%=*}"; _v="${_p#*=}"
    _k="$(echo -n "${_k}" | tr -d '[:space:]')"
    [[ -z "${_k}" ]] && continue
    LABELS_YAML+=$'\n    '"${_k}: \"${_v}\""
  done
fi

# 1. Create the edge resource (idempotent via apply).
echo "Registering ${EDGE_KIND} '${EDGE_NAME}' (type=${EDGE_TYPE})..."
kubectl apply -f - <<EOF
apiVersion: edges.kedge.faros.sh/v1alpha1
kind: ${EDGE_KIND}
metadata:
  name: ${EDGE_NAME}${LABELS_YAML}
spec: {}
EOF

# 2. Extract kcp cluster path from current kubectl config.
CLUSTER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || echo "")
# Extract the cluster path from URL like https://localhost:9443/clusters/abc123
CLUSTER_PATH=""
if [[ "${CLUSTER_URL}" =~ /clusters/([^/]+) ]]; then
  CLUSTER_PATH="${BASH_REMATCH[1]}"
fi
echo "Detected kcp cluster path: ${CLUSTER_PATH:-<none>}"

# 3. Wait for join token (set by the edges provider's token reconciler on create).
TIMEOUT=60
echo "Waiting for join token on ${EDGE_KIND} '${EDGE_NAME}'..."
JOIN_TOKEN=""
elapsed=0
while true; do
  JOIN_TOKEN=$(kubectl get "${EDGE_RESOURCE}.edges.kedge.faros.sh" "${EDGE_NAME}" -o jsonpath='{.status.joinToken}' 2>/dev/null || echo "")
  if [[ -n "${JOIN_TOKEN}" ]]; then
    break
  fi
  if [ "${elapsed}" -ge "${TIMEOUT}" ]; then
    echo "WARNING: Timed out after ${TIMEOUT}s waiting for join token." >&2
    echo "         The Edge token controller may still be starting up." >&2
    break
  fi
  sleep 2
  elapsed=$((elapsed + 2))
  printf "  waiting... (%ds)\r" "${elapsed}"
done
echo ""

# 4. Write .env.edge.<type> for make dev-run-edge TYPE=<type>.
ENV_FILE=".env.edge.${EDGE_TYPE}"
cat > "${ENV_FILE}" <<EOF
# Generated by hack/scripts/dev-edge-setup.sh — do not commit
KEDGE_EDGE_NAME=${EDGE_NAME}
KEDGE_EDGE_TYPE=${EDGE_TYPE}
KEDGE_EDGE_LABELS=${LABELS}
KEDGE_EDGE_CLUSTER=${CLUSTER_PATH}
KEDGE_EDGE_JOIN_TOKEN=${JOIN_TOKEN}
EOF

echo "Done!"
echo "  ${ENV_FILE} written"
if [[ -n "${JOIN_TOKEN}" ]]; then
  echo "  Join token: ${JOIN_TOKEN}"
fi
echo "  Run 'make dev-run-edge TYPE=${EDGE_TYPE}' to start the agent"
