#!/usr/bin/env bash
# Creates an Edge resource (idempotent) and writes .env.edge so that
# `make dev-run-edge` can pick it up.
#
# Usage:
#   hack/scripts/dev-edge-setup.sh <edge-name> <type> [labels]
#
#   type: "kubernetes" (k8s cluster agent) or "server" (bare-metal SSH host)
#
# Requires:
#   - kubectl configured to reach the hub (run `make dev-login` first)

set -euo pipefail

EDGE_NAME="${1:?Usage: $0 <edge-name> <type> [labels]}"
EDGE_TYPE="${2:-kubernetes}"
LABELS="${3:-env=dev,provider=local}"

BINDIR="${BINDIR:-bin}"

if [[ "${EDGE_TYPE}" != "kubernetes" && "${EDGE_TYPE}" != "server" ]]; then
  echo "ERROR: type must be 'kubernetes' or 'server', got: ${EDGE_TYPE}" >&2
  exit 1
fi

# 1. Create Edge resource (idempotent via apply).
echo "Registering Edge '${EDGE_NAME}' (type=${EDGE_TYPE})..."
kubectl apply -f - <<EOF
apiVersion: kedge.faros.sh/v1alpha1
kind: Edge
metadata:
  name: ${EDGE_NAME}
spec:
  type: ${EDGE_TYPE}
EOF

# 2. Extract kcp cluster path from current kubectl config.
CLUSTER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || echo "")
# Extract the cluster path from URL like https://localhost:8443/clusters/abc123
CLUSTER_PATH=""
if [[ "${CLUSTER_URL}" =~ /clusters/([^/]+) ]]; then
  CLUSTER_PATH="${BASH_REMATCH[1]}"
fi
echo "Detected kcp cluster path: ${CLUSTER_PATH:-<none>}"

# 3. Wait for join token (set by the hub token controller on Edge creation).
TIMEOUT=60
echo "Waiting for join token on Edge '${EDGE_NAME}'..."
JOIN_TOKEN=""
elapsed=0
while true; do
  JOIN_TOKEN=$(kubectl get edge "${EDGE_NAME}" -o jsonpath='{.status.joinToken}' 2>/dev/null || echo "")
  if [[ -n "${JOIN_TOKEN}" ]]; then
    break
  fi
  if [ "${elapsed}" -ge "${TIMEOUT}" ]; then
    echo "WARNING: Timed out after ${TIMEOUT}s waiting for join token." >&2
    echo "         The Edge token controller may still be starting up." >&2
    break
  fi
  sleep 2
  elapsed=$((elapsed + 2))
  printf "  waiting... (%ds)\r" "${elapsed}"
done
echo ""

# 4. Write .env.edge for make dev-run-edge.
cat > .env.edge <<EOF
# Generated by hack/scripts/dev-edge-setup.sh — do not commit
KEDGE_EDGE_NAME=${EDGE_NAME}
KEDGE_EDGE_TYPE=${EDGE_TYPE}
KEDGE_EDGE_LABELS=${LABELS}
KEDGE_EDGE_CLUSTER=${CLUSTER_PATH}
KEDGE_EDGE_JOIN_TOKEN=${JOIN_TOKEN}
EOF

echo "Done!"
echo "  .env.edge written"
if [[ -n "${JOIN_TOKEN}" ]]; then
  echo "  Join token: ${JOIN_TOKEN}"
fi
echo "  Run 'make dev-run-edge TYPE=${EDGE_TYPE}' to start the agent"
