#!/usr/bin/env bash
# Registers a non-Kubernetes Server resource for SSH server mode (idempotent).
# Writes .env.server so that `make dev-run-server-agent` can pick it up.
#
# Usage:
#   hack/scripts/dev-server-setup.sh <server-name> [labels]
#
# Requires:
#   - kubectl configured to reach the hub (run `make dev-login` first)

set -euo pipefail

SERVER_NAME="${1:?Usage: $0 <server-name> [labels]}"
LABELS="${2:-env=dev,provider=bare-metal}"

# 1. Create Server resource (idempotent via apply).
echo "Registering server ${SERVER_NAME}..."
kubectl apply -f - <<EOF
apiVersion: kedge.faros.sh/v1alpha1
kind: Server
metadata:
  name: ${SERVER_NAME}
spec:
  displayName: ${SERVER_NAME}
  hostname: localhost
  provider: bare-metal
  region: dev
EOF

# 2. Write .env.server for make dev-run-server-agent.
cat > .env.server <<EOF
# Generated by hack/scripts/dev-server-setup.sh — do not commit
KEDGE_SERVER_NAME=${SERVER_NAME}
KEDGE_SERVER_LABELS=${LABELS}
EOF

echo "Done!"
echo "  .env.server updated"
echo "  Run 'make dev-run-server-agent' to start the agent in server mode"
