#!/usr/bin/env bash
# Creates an Edge resource (idempotent) and writes .env.edge so that
# `make dev-run-edge` can pick it up.
#
# Usage:
#   hack/scripts/dev-edge-setup.sh <edge-name> <type> [labels]
#
#   type: "kubernetes" (k8s cluster agent) or "server" (bare-metal SSH host)
#
# Requires:
#   - kubectl configured to reach the hub (run `make dev-login` first)

set -euo pipefail

EDGE_NAME="${1:?Usage: $0 <edge-name> <type> [labels]}"
EDGE_TYPE="${2:-kubernetes}"
LABELS="${3:-env=dev,provider=local}"

BINDIR="${BINDIR:-bin}"

if [[ "${EDGE_TYPE}" != "kubernetes" && "${EDGE_TYPE}" != "server" ]]; then
  echo "ERROR: type must be 'kubernetes' or 'server', got: ${EDGE_TYPE}" >&2
  exit 1
fi

# 1. Create Edge resource (idempotent via apply).
echo "Registering Edge '${EDGE_NAME}' (type=${EDGE_TYPE})..."
kubectl apply -f - <<EOF
apiVersion: kedge.faros.sh/v1alpha1
kind: Edge
metadata:
  name: ${EDGE_NAME}
spec:
  type: ${EDGE_TYPE}
EOF

# 2. Extract kcp cluster path from current kubectl config.
CLUSTER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || echo "")
# Extract the cluster path from URL like https://localhost:8443/clusters/abc123
CLUSTER_PATH=""
if [[ "${CLUSTER_URL}" =~ /clusters/([^/]+) ]]; then
  CLUSTER_PATH="${BASH_REMATCH[1]}"
fi
echo "Detected kcp cluster path: ${CLUSTER_PATH:-<none>}"

# 3. Write .env.edge for make dev-run-edge.
cat > .env.edge <<EOF
# Generated by hack/scripts/dev-edge-setup.sh — do not commit
KEDGE_EDGE_NAME=${EDGE_NAME}
KEDGE_EDGE_TYPE=${EDGE_TYPE}
KEDGE_EDGE_LABELS=${LABELS}
KEDGE_EDGE_CLUSTER=${CLUSTER_PATH}
EOF

if [[ "${EDGE_TYPE}" == "kubernetes" ]]; then
  NAMESPACE="kedge-system"
  SECRET_NAME="edge-${EDGE_NAME}-kubeconfig"
  OUTPUT_FILE=".edge-kubeconfig"
  TIMEOUT=120

  echo "Waiting for hub kubeconfig secret ${NAMESPACE}/${SECRET_NAME}..."
  elapsed=0
  while true; do
    if kubectl get secret -n "${NAMESPACE}" "${SECRET_NAME}" &>/dev/null; then
      break
    fi
    if [ "${elapsed}" -ge "${TIMEOUT}" ]; then
      echo "WARNING: Timed out after ${TIMEOUT}s waiting for ${SECRET_NAME}." >&2
      echo "         The Edge RBAC controller may still be starting up." >&2
      echo "         You can run 'make dev-run-edge TYPE=kubernetes' anyway and" >&2
      echo "         the secret will be created once the controller is ready." >&2
      break
    fi
    sleep 2
    elapsed=$((elapsed + 2))
    printf "  waiting... (%ds)\r" "${elapsed}"
  done
  echo ""

  if kubectl get secret -n "${NAMESPACE}" "${SECRET_NAME}" &>/dev/null; then
    echo "Extracting hub kubeconfig to ${OUTPUT_FILE}..."
    kubectl get secret -n "${NAMESPACE}" "${SECRET_NAME}" \
      -o jsonpath='{.data.kubeconfig}' | base64 -d > "${OUTPUT_FILE}"
    # Append the kubeconfig path to .env.edge so dev-run-edge can pick it up.
    cat >> .env.edge <<EOF
KEDGE_EDGE_KUBECONFIG=${OUTPUT_FILE}
EOF
  fi
fi

echo "Done!"
echo "  .env.edge written"
echo "  Run 'make dev-run-edge TYPE=${EDGE_TYPE}' to start the agent"
